version: "3.9"
services:
  db:
    image: mysql:8.0
    container_name: umadsede_db
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10

  backend:
    build: ./backend
    container_name: umadsede_backend
    restart: always
    env_file: .env
    environment:
      DASHBOARD_DEFAULT_ADMIN_USER: admin
      DASHBOARD_DEFAULT_ADMIN_PASSWORD: admin123
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    command: ["/app/entrypoint.sh"]
    expose:
      - "8000"

  frontend:
    build: ./frontend
    container_name: umadsede_frontend
    restart: always
    expose:
      - "80"
    depends_on:
      - backend

  caddy:
    image: caddy:2.7
    container_name: umadsede_caddy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    environment:
      - SITE_DOMAIN=${SITE_DOMAIN}
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - frontend

  redis:
    image: redis:7-alpine
    container_name: umadsede_redis
    restart: always

volumes:
  db_data:
  caddy_data:
  caddy_config:
