version: "3.9"
services:
  db:
    image: mysql:8.0
    container_name: umadsede_db
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10

  backend:
    build: ./backend
    container_name: umadsede_backend
    restart: always
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    command: ["/app/entrypoint.sh"]
    expose:
      - "8000"

  frontend:
    build: ./frontend
    container_name: umadsede_frontend
    restart: always
    ports:
      - "${WEB_PORT}:80"
    depends_on:
      - backend

  redis:
    image: redis:7-alpine
    container_name: umadsede_redis
    restart: always

volumes:
  db_data:
